<?php include(dirname(dirname(__FILE__)) . '/' . 'head.php'); ?>
<!-- start site's main content area -->
<section class="content-wrap">
  <div class="container">
    <div class="row">

      <main class="col-md-8 main-content">
                
	<article id=123 class="post tag-aa tag-bb-cc">
	  <div class="post-head">
            <h1 class="post-title"><a href="/post/id123/">测试样式有标签无推荐</a></h1>
            <div class="post-meta">
              <span class="author">作者：<a href="/author/d/">巍哥</a></span> &bull;
              <time class="post-date" datetime="2015年8月31日星期一晚上9点44" title="2015年8月31日星期一晚上9点44">2015年8月31日</time>
            </div>
	  </div>
	  <div class="post-content">
            <p>测试占位L.INUX.XYZ--l.inux.xyz测试占位L.INUX.XYZ--l.inux.xyz测试占位L.INUX.XYZ--l.inux.xyz测试占位L.INUX.XYZ--l.inux.xyz测试占位L.INUX.XYZ--l.inux.xyz测试占位L.INUX.XYZ--l.inux.xyz</p>
	  </div>
	  <div class="post-permalink">
            <a href="/post/id123/" class="btn btn-default">阅读全文</a>
	  </div>
	  
	  <footer class="post-footer clearfix">
            <div class="pull-left tag-list">
              <i class="fa fa-folder-open-o"></i>
              <a href="/tag/aa/">aa</a>, <a href="/tag/bb-cc/">bb cc名字任意起</a>
            </div>
            <div class="pull-right share">
            </div>
	  </footer>
	</article>

	<article id=124 class="post tag-zz tag-xx-yy featured">
	  <div class="featured" title="推荐文章">
            <i class="fa fa-star"></i>
	  </div>
	  <div class="post-head">
            <h1 class="post-title"><a href="/post/id124/">测试样式有标签有推荐</a></h1>
            <div class="post-meta">
              <span class="author">作者：<a href="/author/d/">巍哥</a></span> &bull;
              <time class="post-date" datetime="2015年8月13日星期四晚上7点06" title="2015年8月13日星期四晚上7点06">2015年8月13日</time>
            </div>
	  </div>
	  <div class="post-content">
            <p>测试占位L.INUX.XYZ--l.inux.xyz测试占位L.INUX.XYZ--l.inux.xyz测试占位L.INUX.XYZ--l.inux.xyz测试占位L.INUX.XYZ--l.inux.xyz.....</p>
	  </div>
	  <div class="post-permalink">
            <a href="/post/id124/" class="btn btn-default">阅读全文</a>
	  </div>

	  <footer class="post-footer clearfix">
            <div class="pull-left tag-list">
              <i class="fa fa-folder-open-o"></i>
              <a href="/tag/zz/">标签ZZ</a>, <a href="/tag/xx-yy/">XY</a>
            </div>
            <div class="pull-right share">
            </div>
	  </footer>
	</article>

	<article id=125 class="post">
	  <div class="post-head">
            <h1 class="post-title"><a href="/post/id125/">测试样式无标签无推荐</a></h1>
            <div class="post-meta">
              <span class="author">作者：<a href="/author/d/">巍哥</a></span> &bull;
              <time class="post-date" datetime="2015年3月15日星期日晚上11点43" title="2015年3月15日星期日晚上11点43">2015年3月15日</time>
            </div>
	  </div>
	  <div class="post-content">
            <p>l.inux.xyz测试占位L.INUX.XYZ--l.inux.xyz测试占位L.INUX.XYZ--l.inux.xyz</p>
	  </div>
	  <div class="post-permalink">
            <a href="/post/id125/" class="btn btn-default">阅读全文</a>
	  </div>
	  
	  <footer class="post-footer clearfix">
            <div class="pull-left tag-list">
              <i class="fa fa-folder-open-o"></i>
            </div>
            <div class="pull-right share">
            </div>
	  </footer>
	</article>

        <article id=126 class="post featured">
          <div class="featured" title="推荐文章">
            <i class="fa fa-star"></i>
          </div>
          <div class="post-head">
            <h1 class="post-title"><a href="/post/id126/">测试样式无标签有推荐</a></h1>
            <div class="post-meta">
              <span class="author">作者：<a href="/author/d/">巍哥</a></span> &bull;
              <time class="post-date" datetime="2015年3月15日星期日晚上11点43" title="2015年3月15日星期日晚上11点43">2015年3月15日</time>
            </div>
          </div>
          <div class="post-content">
            <p>l.inux.xyz测试占位L.INUX.XYZ--l.inux.xyz测试占位L.INUX.XYZ--l.inux.xyz</p>
          </div>
          <div class="post-permalink">
            <a href="/post/id126/" class="btn btn-default">阅读全文</a>
          </div>

          <footer class="post-footer clearfix">
            <div class="pull-left tag-list">
              <i class="fa fa-folder-open-o"></i>
            </div>
            <div class="pull-right share">
            </div>
          </footer>
        </article>


	<nav class="pagination" role="navigation">
          <a class="newer-posts" href="/"><i class="fa fa-angle-left"></i></a>
	  <span class="page-number">第 1 页 &frasl; 共 4 页</span>
          <a class="older-posts" href="/page/2/"><i class="fa fa-angle-right"></i></a>
	</nav>

      </main>

      <?php include(dirname(dirname(__FILE__)) . '/' . 'side.php'); ?>

    </div>
  </div>
</section>

<?php include(dirname(dirname(__FILE__)) . '/' . 'foot.php'); ?>
