<?php
include(dirname(dirname(__FILE__)) . '/' . 'head.php');
$art = ${'art'};
$prev_art = ${'prev_art'};
$next_art = ${'next_art'};
?>
<section class="content-wrap">
  <div class="container">
    <div class="row">

      <main class="col-md-8 main-content">

<?php
$tags = explode(',', $art['tag']);

$t_str = '';
if (count($tags) > 0) {
    foreach ($tags as $tag) {
        $t_str .= 'tag-' . $tag . ' ';
    }
}

echo '<article id="'.$art['a_id'].'" class="post '.$t_str.'featured">';

echo '<header class="post-head">';
echo '<h1 class="post-title">'.$art['title'].'</h1>';
echo '<section class="post-meta">';
echo '<span class="author">作者：<a href="/author/'.$art['u_id'].'">'.$art['author'].'</a></span> &bull; &nbsp';
echo '<time class="post-date" datetime="'.$art['date_added'].'" title="'.$art['date_added'].'">'.$art['date_added'].'</time>';
echo '</section>';
echo '</header>';


echo '<section class="post-content">';
$Parsedown = new Our_Parsedown();
echo $Parsedown->text($art['content']);
echo '</section>';

echo '<footer class="post-footer clearfix">';
echo '<div class="pull-left tag-list">';
echo '<i class="fa fa-folder-open-o"></i>';

if (count($tags) > 0) {
  foreach ($tags as $k => $v) {
    if ($k == 0) {
      echo '<a href="/tag/'.$v.'">'.$v.'</a>';
    }
    else {
      echo ', <a href="/tag/'.$v.'">'.$v.'</a>';
    }
  }
}

echo '</div>';
echo '<div class="pull-right share">';
echo '<div class="bdsharebuttonbox share-icons">';
echo '<a href="#" class="bds_more" data-cmd="more"></a>';
echo '<a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>';
echo '<a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>';
echo '<a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a>';
echo '<a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a>';
echo '<a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '</article>';

echo '<div class="about-author clearfix">';
echo '<a href="/author/'.$art['u_id'].'"><img src="'.$art['photo'].'" alt="'.$art['username'].'" class="avatar pull-left"></a>';

echo '<div class="details">';
echo '<div class="author">关于作者 <a href="/author/'.$art['u_id'].'">'.$art['username'].'</a></div>';
echo '<div class="meta-info">';
echo '<span class="loaction"><i class="fa fa-home"></i>'.$art['location'].'</span>';
echo '<span class="website"><i class="fa fa-globe"></i><a href="'.$art['website'].'" targer="_blank">个人网站/博客</a></span>';
echo '</div>';
echo '</div>';
echo '</div>';

echo '<div class="prev-next-wrap clearfix">';

if ($prev_art) {
    echo '<a class="btn btn-default" href="/post/'.$prev_art['a_id'].'"><i class="fa fa-angle-left fa-fw"></i>'.$prev_art['title'].'</a>';
}
echo '&nbsp;&nbsp;';
if ($next_art) {
    echo '<a class="btn btn-default" href="/post/'.$next_art['a_id'].'">'.$next_art['title'].'<i class="fa fa-angle-right fa-fw"></i></a>';
}
echo '</div>';

?>
  </main>

<?php include(dirname(dirname(__FILE__)) . '/' . 'side.php'); ?>

    </div>
  </div>
</section>

<?php include(dirname(dirname(__FILE__)) . '/' . 'foot.php'); ?>